-- Backfills a gap in this repo's migration history. This file is
-- intentionally a no-op -- it applies zero real schema changes.
--
-- packages/db/src/migrations/meta/ was missing the snapshot json for every
-- migration between 0046 and 0088 (only 0000/0001/0032/0045 were ever
-- committed, despite _journal.json listing 89 entries). Without those
-- snapshots, `drizzle-kit generate` had no accurate record of the schema
-- between 0045 and today, so asking it to generate a migration produced a
-- huge reconstructed diff straight from the stale 0045 baseline: every
-- table/column added since 0045 showed up as "new" (harmless,
-- `CREATE TABLE IF NOT EXISTS`), but objects renamed/dropped since 0045
-- (e.g. model_poses -> model_pose_assets, per the real 0047_drop_model_poses
-- migration) showed up as unguarded `DROP TABLE`/`DROP CONSTRAINT`/
-- `ADD COLUMN` statements with no existence guards.
--
-- Those statements describe things that ALREADY happened via the real,
-- historical migrations 0046-0088 (already applied to every environment,
-- including a from-scratch test database -- confirmed directly, this repo's
-- test harness in apps/api/test/helpers/containers.ts replays the full
-- migration history via drizzle-orm's own migrator against a fresh database
-- for every test file, so any migration entry must be safe to run from a
-- true zero state, not just against an already-migrated one). Applying the
-- originally-generated version of this file literally would have re-run
-- already-done work: on a from-scratch database it would fail at
-- `DROP TABLE "model_poses" CASCADE` (dropped for real back in migration
-- 0047, so it's already gone by the time execution reaches this entry
-- either way); on an already-migrated database, the same statement fails
-- for the same reason. There is no schema state in which that generated
-- SQL is safe to execute as-is.
--
-- Rather than hand-patch every one of those statements with IF EXISTS/IF
-- NOT EXISTS guards (this file, before this rewrite, was ~420 lines
-- reconstructing 40+ tables' worth of already-real history), this file's
-- SQL body is reduced to a genuine no-op. Its only real job is existing at
-- all: giving `pnpm db:generate` a *snapshot* (see the paired
-- meta/0090_snapshot.json) that accurately reflects the current schema, so
-- future migrations diff against reality instead of the stale 0045
-- baseline. Verified directly via psql before this file was finalized: a
-- from-scratch database (full migration history 0000-0088, then this file)
-- and the long-running dev database both already match every table/column
-- this snapshot describes -- there is nothing left for this file to do.
--
-- If you are adding a new migration after this one: nothing about this
-- file should ever need to run or be edited again. If `pnpm db:generate`
-- ever proposes touching model_poses/model_pose_assets again, stop and
-- investigate rather than assuming it is another instance of this same gap.
SELECT 1;
