CREATE TABLE IF NOT EXISTS "shopify_store_disabled_funnel_rules" (
	"store_id" uuid NOT NULL,
	"rule_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "shopify_store_disabled_funnel_rules_store_id_rule_id_pk" PRIMARY KEY("store_id","rule_id")
);
--> statement-breakpoint
-- NOTE (2026-09-07, Task 2 of the shopify-admin-support-chat plan): this migration
-- was generated by `pnpm db:generate` against meta/0194_snapshot.json, which was
-- already stale/drifted on dev before this branch existed — several separately
-- developed feature branches' snapshot chains diverged and were merged into dev
-- sequentially, so 0194's snapshot was missing columns that real earlier
-- migrations (0186/0187/0190) had already added. drizzle-kit diffed against that
-- stale snapshot and re-proposed those already-applied columns as "new" here.
-- Harmless on a dev DB that had already recorded this file's hash as applied
-- (from before the drift was noticed), but fatal (`column already exists`) on
-- any fresh database, which is exactly what every integration test's
-- `startContainers()` creates. Removed here: the six chatbot_conversations/
-- messages ADD COLUMNs (source/category/priority/subject on conversations,
-- attachment_key/attachment_type on messages — all already in 0190) and the
-- two garment_subcategories ADD COLUMNs (already in 0186/0187).
--
-- Corrected 2026-09-07 by final branch review: everything left below is ALSO
-- not new — the funnel-rules table/constraints/index are verbatim duplicates
-- of 0189_great_thor_girl.sql (same table, same constraint names, same index),
-- and the SET DEFAULT is a harmless repeat of 0190. So this file is a complete
-- no-op at the SQL level in every environment; there is nothing genuinely new
-- in it. It's kept anyway — deleting it would also require hand-editing
-- drizzle's journal and losing the audit trail of what drizzle-kit originally
-- proposed here — and the actual fix for the drift is the corrected
-- meta/0195_snapshot.json generated alongside this file, which is what makes
-- later `db:generate` runs diff against accurate state instead of re-proposing
-- these same statements again.
ALTER TABLE "chatbot_conversations" ALTER COLUMN "status" SET DEFAULT 'OPEN';--> statement-breakpoint
ALTER TABLE "shopify_funnel_rules" ALTER COLUMN "store_id" DROP NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "shopify_store_disabled_funnel_rules" ADD CONSTRAINT "shopify_store_disabled_funnel_rules_store_id_shopify_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "public"."shopify_stores"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "shopify_store_disabled_funnel_rules" ADD CONSTRAINT "shopify_store_disabled_funnel_rules_rule_id_shopify_funnel_rules_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."shopify_funnel_rules"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "shopify_funnel_rules_one_global_per_basket_idx" ON "shopify_funnel_rules" USING btree ("funnel_template_id") WHERE "shopify_funnel_rules"."store_id" is null;--> statement-breakpoint
ALTER TABLE "shopify_funnel_rules" DROP COLUMN IF EXISTS "mode";