export const keys = {
  inputGarment: (jobId: string) => `inputs/${jobId}/garment.jpg`,
  output: (jobId: string) => `outputs/${jobId}/result.png`,
  outputThumb: (jobId: string) => `outputs/${jobId}/result.thumb.jpg`,
  catalogItem: (typeSlug: string, id: string) => `catalog/${typeSlug}/${id}.jpg`,
  catalogThumb: (typeSlug: string, id: string) => `catalog/${typeSlug}/${id}.thumb.jpg`,
  catalogCategoryThumb: (typeSlug: string, id: string) => `catalog/${typeSlug}/cat-${id}.thumb.jpg`,
  modelFace: (id: string) => `models/faces/${id}.jpg`,
  modelFaceThumb: (id: string) => `models/faces/${id}.thumb.jpg`,
  modelFaceSide: (id: string) => `models/faces/${id}.faceside.jpg`,
  modelBackground: (id: string) => `models/backgrounds/${id}.jpg`,
  modelBackgroundThumb: (id: string) => `models/backgrounds/${id}.thumb.jpg`,
  modelBackgroundComfy: (id: string) => `models/backgrounds/${id}.bgcomfy.jpg`,
  modelPose: (id: string) => `models/poses/${id}.jpg`,
  modelPoseThumb: (id: string) => `models/poses/${id}.thumb.jpg`,
  modelPoseFaceSide: (id: string) => `models/poses/${id}.faceside.jpg`,
  modelPoseBgComfy: (id: string) => `models/poses/${id}.bgcomfy.jpg`,
  subcategoryThumb: (id: string) => `models/subcategories/${id}.thumb.jpg`,
  subcategoryTemplate: (id: string) => `models/templates/${id}.jpg`,
  subcategoryTemplateThumb: (id: string) => `models/templates/${id}.thumb.jpg`,
  tryonSample: (categoryId: string, sampleId: string) =>
    `tryon/categories/${categoryId}/${sampleId}.jpg`,
  tryonSampleThumb: (categoryId: string, sampleId: string) =>
    `tryon/categories/${categoryId}/${sampleId}.thumb.jpg`,
};
