// The two ways a video can be sourced: an existing completed AI Vastra job
// (from the catalogues grid), or a fresh upload of any image the user owns —
// not required to have been generated by AI Vastra at all. Shared by
// page.tsx, SourcePanel.tsx, and ConfigPanel.tsx.
export type ImageSource =
  | { kind: 'existing'; jobId: string }
  | { kind: 'upload'; r2Key: string; previewUrl: string };
