import type { Metadata } from 'next';
import { LegalPage, LegalSection } from '@/components/legal-page';

export const metadata: Metadata = {
  title: 'Privacy Policy — Ai Vastra',
};

const p: React.CSSProperties = { margin: '0 0 12px' };
const ul: React.CSSProperties = { margin: '0 0 12px', paddingLeft: 20 };

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="August 25, 2026">
      <p style={p}>
        AI Vastra ("AI Vastra", "we", "us", or "our") is committed to protecting the privacy and
        security of information processed through our services.
      </p>
      <p style={p}>
        This Privacy Policy explains how AI Vastra collects, uses, processes, stores, transfers, and
        protects information when you access or use our websites, web application, WordPress plugin,
        developer API, Shopify app, Virtual Try-On technology, and other related products and
        services (collectively, the "Services"). AI Vastra may provide its Services through or in
        connection with third-party e-commerce platforms, content-management systems, websites,
        mobile applications, APIs, plugins, kiosks, digital displays, and other technology platforms
        — this Privacy Policy applies generally to AI Vastra regardless of the platform, device,
        integration, or method through which the Services are accessed.
      </p>

      <LegalSection heading="1. Definitions">
        <ul style={ul}>
          <li>
            <strong>"Merchant"</strong> means a business, retailer, brand, website owner,
            organization, or other entity using AI Vastra.
          </li>
          <li>
            <strong>"Customer" or "End User"</strong> means an individual who interacts with a
            Merchant's website, application, store, kiosk, device, or Virtual Try-On experience.
          </li>
          <li>
            <strong>"Uploaded Content"</strong> means photographs, selfies, images, product images,
            videos, text, or other content submitted to the Services.
          </li>
          <li>
            <strong>"Generated Content"</strong> means images or other content generated by AI
            Vastra in response to an authorized request.
          </li>
          <li>
            <strong>"Personal Information" or "Personal Data"</strong> means information that
            identifies, relates to, describes, or can reasonably be associated with an individual,
            as defined under applicable law.
          </li>
        </ul>
        <p style={p}>
          Corporate Office: #904, 9th Floor, Asian Sun City, Kondapur, Hyderabad. Head Office:
          Salumuri Vari St, Innespeta, Rajahmundry, Andhra Pradesh.
        </p>
      </LegalSection>

      <LegalSection heading="2. Information we collect">
        <p style={p}>
          <strong>Merchant information:</strong> business or store name; website/store URL; name and
          contact information; account information (including a hashed password or a Google account
          identifier if you sign in with Google); billing and subscription information where
          applicable; service configuration and settings; product and catalog information;
          application logs; security information; and communications with our support team.
        </p>
        <p style={p}>
          <strong>Customer information:</strong> depending on the functionality being used,
          customers may voluntarily provide photographs or selfies, images of themselves, product
          selections, product images, Virtual Try-On images, device and browser information, IP
          address and technical information, and information submitted through forms or
          communications. AI Vastra does not intentionally require customers to provide information
          that is not reasonably necessary for the requested functionality.
        </p>
        <p style={p}>
          <strong>Payment information:</strong> we do not collect or store your card details.
          Payments are handled entirely by Razorpay or, for Shopify merchants, by Shopify's own
          billing system — we only receive confirmation that a payment succeeded and its amount.
        </p>
        <p style={p}>
          <strong>Store/site integration data:</strong> if you connect a Shopify store or WordPress
          site, we store the store domain or site origin, a hashed version of any API key you
          generate, and product identifiers needed to render the try-on button — not your store's
          admin credentials.
        </p>
      </LegalSection>

      <LegalSection heading="3. Virtual Try-On processing & AI-generated content">
        <p style={p}>
          AI Vastra provides AI-powered Virtual Try-On technology that may allow a customer to
          upload a photograph or selfie and generate an image showing how a selected product may
          appear on that person. Uploaded photographs may be processed by AI Vastra and by
          authorized third-party infrastructure or technology providers that assist us in delivering
          the Services. Processing may include receiving uploaded images; temporarily storing
          images; processing images using artificial intelligence; processing product images and
          related information; generating Virtual Try-On results; returning generated results to the
          requesting customer or Merchant; detecting and preventing misuse or abuse; and deleting or
          anonymizing information according to our retention practices.
        </p>
        <p style={p}>
          <strong>AI-generated content disclaimer:</strong> AI Vastra uses artificial intelligence
          and machine-learning technologies. AI-generated results may contain inaccuracies,
          distortions, artifacts, unexpected modifications, or other errors, and AI Vastra does not
          guarantee that a Virtual Try-On image will accurately represent a person's actual
          appearance, body proportions, facial features, clothing size or fit, garment positioning,
          product color, texture, pattern, material, shape, or design details. Virtual Try-On
          results are provided primarily for visualization and informational purposes — customers
          should rely on actual product descriptions, measurements, size charts, and applicable
          Merchant policies when making purchasing decisions.
        </p>
        <p style={p}>
          Customer-uploaded photographs are processed for purposes reasonably necessary to provide
          the requested Virtual Try-On functionality. AI Vastra does not claim ownership of customer
          photographs; by submitting a photograph you grant AI Vastra and its authorized service
          providers the limited rights necessary to receive and process the content, generate the
          requested result, store it temporarily where technically necessary, transmit it through
          our infrastructure, maintain and secure the Services, prevent fraud and abuse,
          troubleshoot technical problems, and comply with applicable legal obligations. We do not
          sell customer-uploaded photographs for advertising purposes.
        </p>
      </LegalSection>

      <LegalSection heading="4. How we use this information">
        <ul style={ul}>
          <li>To generate and deliver your virtual try-on or catalogue results.</li>
          <li>To operate your account, process credit purchases, and provide customer support.</li>
          <li>
            To secure the Service — detecting abuse, enforcing rate limits, and preventing fraud.
          </li>
          <li>To understand feature usage in aggregate and improve the Service.</li>
          <li>To comply with legal obligations and respond to lawful requests.</li>
        </ul>
        <p style={p}>
          AI Vastra does not intentionally use customer-uploaded photographs or Generated Content to
          train general-purpose AI models unless you have been separately informed and the necessary
          authorization has been obtained. Where third-party AI or technology providers are used,
          information may be processed by those providers as necessary to provide the Services. We
          do not sell customer photographs or Generated Content for advertising purposes.
        </p>
        <p style={p}>
          We may also create aggregated or de-identified information from data processed through the
          Service and, where permitted by law, use it for analytics, performance measurement,
          security, product development, service improvement, troubleshooting, and business
          planning. We will not intentionally use properly de-identified information to identify an
          individual.
        </p>
      </LegalSection>

      <LegalSection heading="5. Who we share information with">
        <p style={p}>
          AI Vastra may use third-party service providers to operate and support the Services,
          including:
        </p>
        <ul style={ul}>
          <li>
            <strong>Razorpay</strong> — processes direct credit-pack payments. See{' '}
            <a href="https://razorpay.com/privacy/" style={{ color: 'inherit' }}>
              Razorpay's Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Shopify</strong> — for stores that install our Shopify app, handles billing and
            provides the store/product data needed to render the try-on experience.
          </li>
          <li>
            <strong>Google</strong> — only if you choose to sign in with Google, to verify your
            identity.
          </li>
          <li>
            Cloud hosting, data storage, AI/image processing, content delivery, security,
            application monitoring, analytics, customer support, and communications providers we use
            to operate and secure the Services.
          </li>
        </ul>
        <p style={p}>
          Third-party providers may process information on our behalf and may operate in countries
          other than the one in which the information was collected. We seek to use appropriate
          contractual, technical, and organizational safeguards where required by applicable law. We
          do not sell your personal information, and we do not use third-party advertising trackers.
        </p>
      </LegalSection>

      <LegalSection heading="6. Data retention">
        <p style={p}>
          AI Vastra retains information only for as long as reasonably necessary for the purposes
          described in this Privacy Policy — providing the Services, processing Virtual Try-On
          requests, maintaining security, preventing fraud and abuse, resolving disputes, enforcing
          agreements, complying with legal obligations, and maintaining legitimate business records.
          Uploaded photographs and Generated Content may be deleted automatically after processing
          or after a defined period depending on the applicable Service configuration; information
          may remain temporarily in encrypted backups, disaster-recovery systems, or security logs
          we are legally required to retain. In particular, on our platform today:
        </p>
        <ul style={ul}>
          <li>Account data is kept while your account is active.</li>
          <li>
            Uploaded images and generated results are kept as part of your history until you delete
            them or delete your account.
          </li>
          <li>
            An uploaded image that is never used to start a generation is automatically deleted
            after 24 hours.
          </li>
          <li>
            Aggregate storefront widget interaction data is retained for a limited period (currently
            up to 400 days) and is used only for reporting — never for credit, access, or
            authorization decisions.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="7. Your rights & deletion requests">
        <p style={p}>
          Subject to applicable law and contractual obligations, you may request access to,
          correction of, or deletion of your Personal Data or Uploaded Content — including copyright
          complaints about content processed through AI Vastra — by contacting support@aivastra.com.
          We may need to verify your identity and authority before processing a request; certain
          information may be retained where required or permitted by law. For Shopify merchants,
          uninstalling the app triggers an automated data-erasure process for your store's data,
          consistent with Shopify's data-protection requirements. We aim to honor deletion requests
          within [TIMEFRAME — LEGAL TO CONFIRM; not specified in AI Vastra's own published policy
          either].
        </p>
        <p style={p}>
          Depending on applicable law, you may have additional rights — to object to certain
          processing, withdraw consent where applicable, request a portable copy of your data, or
          lodge a complaint with your local data-protection authority (for example, under GDPR or
          India's Digital Personal Data Protection Act).
        </p>
      </LegalSection>

      <LegalSection heading="8. Security">
        <p style={p}>
          We use reasonable technical and organizational measures designed to protect information
          against unauthorized access, disclosure, alteration, loss, destruction, and misuse,
          including encryption in transit and at rest where appropriate, access controls,
          authentication mechanisms, monitoring and logging, and security incident response
          procedures. Stored files are held in access-controlled object storage, and sensitive
          credentials (including third-party access tokens) are encrypted at rest.
        </p>
        <p style={p}>
          However, no Internet transmission, cloud infrastructure, software application, or storage
          system can be guaranteed to be completely secure. Accordingly, AI Vastra does not
          guarantee the absolute security of information.
        </p>
      </LegalSection>

      <LegalSection heading="9. Cookies and similar technologies">
        <p style={p}>
          We use essential cookies to keep you signed in (an access token and a refresh token, the
          latter accessible only to our server, not to page scripts), maintain security, remember
          settings, and understand usage. We do not use third-party advertising or cross-site
          tracking cookies. Merchants are responsible for ensuring that any additional tracking
          technologies used on their own websites or stores comply with applicable law.
        </p>
      </LegalSection>

      <LegalSection heading="10. Children's privacy">
        <p style={p}>
          The Services are not directed at, and should not be used by, anyone under 18. AI Vastra
          does not knowingly collect personal information directly from children where prohibited by
          applicable law. Merchants must not use AI Vastra to collect or process children's
          photographs or Personal Data unless all legally required permissions, consents, and
          safeguards have been obtained. If we become aware of information collected in violation of
          applicable children's privacy requirements, we may take reasonable steps to delete it.
        </p>
      </LegalSection>

      <LegalSection heading="11. International data transfers">
        <p style={p}>
          AI Vastra and its service providers may process or store information in countries other
          than your own. [LEGAL TO CONFIRM: AI Vastra's own published policy states only that it
          will "seek to implement appropriate legally recognized transfer mechanisms and safeguards"
          without naming a specific hosting region — flag if a named region/safeguard should be
          disclosed here instead.]
        </p>
      </LegalSection>

      <LegalSection heading="12. Responsibility for uploaded content & Merchant responsibilities">
        <p style={p}>
          The person or organization uploading content to AI Vastra is responsible for ensuring they
          have all necessary rights, permissions, licenses, and consents to upload and process that
          content (customer photographs, model photographs, product photographs, brand images,
          logos, trademarks, and other intellectual property). AI Vastra does not independently
          verify ownership, licensing, consent, or authorization for every item uploaded to the
          Services.
        </p>
        <p style={p}>
          Merchants are responsible for providing their own customers with appropriate privacy
          notices and obtaining any consent, authorization, or other lawful basis required by
          applicable law before collecting or submitting customer information to AI Vastra, and for
          complying with applicable privacy, data-protection, consumer-protection,
          intellectual-property, and advertising laws. AI Vastra provides technology and
          infrastructure and does not provide legal advice to Merchants.
        </p>
      </LegalSection>

      <LegalSection heading="13. Changes to this policy">
        <p style={p}>
          We may update this Privacy Policy periodically to reflect changes in our Services,
          technology, business operations, security practices, or legal requirements. When
          appropriate, we will notify you of material changes through our website, Services, email,
          or other reasonable methods, and the updated version will carry a revised effective date.
        </p>
      </LegalSection>

      <LegalSection heading="14. Grievance officer / contact">
        <p style={p}>
          For privacy questions, requests, or copyright/IP complaints: support@aivastra.com, +91
          7729883692.
        </p>
        <p style={p}>
          Corporate Office: #904, 9th Floor, Asian Sun City, Kondapur, Hyderabad.
          <br />
          Head Office: Salumuri Vari St, Innespeta, Rajahmundry, Andhra Pradesh.
        </p>
        <p style={p}>
          [LEGAL TO CONFIRM: a named Grievance Officer, required under India's IT Rules for a
          locally operating service — AI Vastra's own currently-published Privacy Policy gives only
          the contact details above, without naming a specific officer either, so this is genuinely
          still open, not an oversight introduced here.]
        </p>
      </LegalSection>

      <LegalSection heading="15. Important legal notice">
        <p style={p}>
          AI Vastra provides technology and infrastructure for AI-powered Virtual Try-On and related
          services. AI Vastra does not provide legal, privacy, copyright, intellectual-property,
          compliance, or regulatory advice. Merchants and users are responsible for ensuring that
          their use of AI Vastra, their uploaded content, their customer interactions, and their
          business practices comply with applicable laws and third-party rights. This Privacy Policy
          does not guarantee compliance with every law or regulation applicable to every user,
          Merchant, country, jurisdiction, business model, or use of the Services. Where
          appropriate, Merchants and users should obtain independent legal advice.
        </p>
        <p style={p}>
          By accessing or using the Services, you acknowledge that you have read and understood this
          Privacy Policy.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
